services:
  mtc-agent:
    container_name: mtc-agent
    image: mtc-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DEVICE_XML="Device.xml"
    volumes:
      - ./agent/agent.cfg:/mtconnect/config/agent.cfg
      - ../agent/Devices.xml:/mtconnect/config/Devices.xml
      - ./log:/mtconnect/log
      - ../twin:/mtconnect/data/demo/twin
    restart: unless-stopped