/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.7.0, using .NET Server 4.1.0 template (version 0)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>
**
** Copyright (c) 2006-2025 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://ifw.uni-hannover.de/umatiConnectDMG/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Created: 21.03.2025
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace ifw.umatiConnect
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class DataTypes
    {
    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the DMGMilltap700 Object.
        /// </summary>
        public const uint Machines_DMGMilltap700 = 5003;

        /// <summary>
        /// The identifier for the Equipment Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Equipment = 5004;

        /// <summary>
        /// The identifier for the Identification Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification = 5005;

        /// <summary>
        /// The identifier for the SoftwareIdentification Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_SoftwareIdentification = 5001;

        /// <summary>
        /// The identifier for the MDC Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC = 5002;

        /// <summary>
        /// The identifier for the Monitoring Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring = 5006;

        /// <summary>
        /// The identifier for the MachineTool Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool = 5007;

        /// <summary>
        /// The identifier for the MachineryItemState Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState = 5013;

        /// <summary>
        /// The identifier for the OperationCounters Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters = 5014;

        /// <summary>
        /// The identifier for the Stacklight Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight = 5015;

        /// <summary>
        /// The identifier for the Light_1 Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_1 = 5016;

        /// <summary>
        /// The identifier for the Light_2 Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_2 = 5017;

        /// <summary>
        /// The identifier for the Light_3 Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_3 = 5018;

        /// <summary>
        /// The identifier for the Light_4 Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_4 = 5019;

        /// <summary>
        /// The identifier for the Notification Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Notification = 5008;

        /// <summary>
        /// The identifier for the Production Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production = 5009;

        /// <summary>
        /// The identifier for the ActiveProgram Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram = 5010;

        /// <summary>
        /// The identifier for the State Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_State = 5011;

        /// <summary>
        /// The identifier for the http://ifw.uni-hannover.de/umatiConnectDMG/ Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG_ = 5012;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class ObjectTypes
    {
    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class Methods
    {
    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the Manufacturer Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_Manufacturer = 6001;

        /// <summary>
        /// The identifier for the ProductInstanceUri Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_ProductInstanceUri = 6002;

        /// <summary>
        /// The identifier for the SerialNumber Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_SerialNumber = 6003;

        /// <summary>
        /// The identifier for the Identifier Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_Identifier = 6010;

        /// <summary>
        /// The identifier for the SoftwareRevision Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_SoftwareRevision = 6011;

        /// <summary>
        /// The identifier for the FeedOverride Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride = 6012;

        /// <summary>
        /// The identifier for the EngineeringUnits Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EngineeringUnits = 6020;

        /// <summary>
        /// The identifier for the EURange Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EURange = 6021;

        /// <summary>
        /// The identifier for the CurrentState Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState = 6022;

        /// <summary>
        /// The identifier for the EffectiveDisplayName Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_EffectiveDisplayName = 6030;

        /// <summary>
        /// The identifier for the Id Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Id = 6023;

        /// <summary>
        /// The identifier for the Name Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Name = 6031;

        /// <summary>
        /// The identifier for the Number Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Number = 6032;

        /// <summary>
        /// The identifier for the OperationDuration Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_OperationDuration = 6029;

        /// <summary>
        /// The identifier for the PowerOnDuration Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_PowerOnDuration = 6024;

        /// <summary>
        /// The identifier for the OperationMode Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_MachineTool_OperationMode = 6004;

        /// <summary>
        /// The identifier for the NumberInList Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_NumberInList = 6034;

        /// <summary>
        /// The identifier for the SignalColor Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalColor = 6035;

        /// <summary>
        /// The identifier for the SignalMode Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalMode = 6036;

        /// <summary>
        /// The identifier for the SignalOn Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalOn = 6037;

        /// <summary>
        /// The identifier for the NumberInList Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_NumberInList = 6039;

        /// <summary>
        /// The identifier for the SignalColor Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalColor = 6042;

        /// <summary>
        /// The identifier for the SignalMode Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalMode = 6044;

        /// <summary>
        /// The identifier for the SignalOn Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalOn = 6043;

        /// <summary>
        /// The identifier for the NumberInList Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_NumberInList = 6040;

        /// <summary>
        /// The identifier for the SignalColor Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalColor = 6045;

        /// <summary>
        /// The identifier for the SignalMode Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalMode = 6046;

        /// <summary>
        /// The identifier for the SignalOn Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalOn = 6047;

        /// <summary>
        /// The identifier for the NumberInList Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_NumberInList = 6041;

        /// <summary>
        /// The identifier for the SignalColor Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalColor = 6048;

        /// <summary>
        /// The identifier for the SignalMode Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalMode = 6049;

        /// <summary>
        /// The identifier for the SignalOn Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalOn = 6050;

        /// <summary>
        /// The identifier for the StacklightMode Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Monitoring_Stacklight_StacklightMode = 6038;

        /// <summary>
        /// The identifier for the EmergencyStopTriggered Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Notification_EmergencyStopTriggered = 6033;

        /// <summary>
        /// The identifier for the CurrentRunTime Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_CurrentRunTime = 6025;

        /// <summary>
        /// The identifier for the DesiredParts Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_DesiredParts = 6027;

        /// <summary>
        /// The identifier for the JobIdentifier Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_JobIdentifier = 6026;

        /// <summary>
        /// The identifier for the Name Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_Name = 6005;

        /// <summary>
        /// The identifier for the NumberInList Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_NumberInList = 6006;

        /// <summary>
        /// The identifier for the PartCounter Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_PartCounter = 6028;

        /// <summary>
        /// The identifier for the CurrentState Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState = 6007;

        /// <summary>
        /// The identifier for the Id Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Id = 6008;

        /// <summary>
        /// The identifier for the Number Object.
        /// </summary>
        public const uint Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Number = 6009;

        /// <summary>
        /// The identifier for the IsNamespaceSubset Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__IsNamespaceSubset = 6013;

        /// <summary>
        /// The identifier for the NamespacePublicationDate Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespacePublicationDate = 6014;

        /// <summary>
        /// The identifier for the NamespaceUri Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceUri = 6015;

        /// <summary>
        /// The identifier for the NamespaceVersion Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceVersion = 6016;

        /// <summary>
        /// The identifier for the StaticNodeIdTypes Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNodeIdTypes = 6017;

        /// <summary>
        /// The identifier for the StaticNumericNodeIdRange Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNumericNodeIdRange = 6018;

        /// <summary>
        /// The identifier for the StaticStringNodeIdPattern Object.
        /// </summary>
        public const uint Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticStringNodeIdPattern = 6019;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all DataTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class DataTypeIds
    {
    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Methods in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class MethodIds
    {
    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the Machines_DMGMilltap700 Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700 = new ExpandedNodeId(Objects.Machines_DMGMilltap700, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Equipment Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Equipment = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Equipment, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Identification, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_SoftwareIdentification Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_SoftwareIdentification = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Identification_SoftwareIdentification, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_MachineTool, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_Stacklight, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_1 Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_1 = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_Stacklight_Light_1, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_2 Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_2 = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_Stacklight_Light_2, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_3 Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_3 = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_Stacklight_Light_3, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_4 Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_4 = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Monitoring_Stacklight_Light_4, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Notification Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Notification = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Notification, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Production, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Production_ActiveProgram, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_State Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_State = new ExpandedNodeId(Objects.Machines_DMGMilltap700_Production_ActiveProgram_State, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG_ Object.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG_ = new ExpandedNodeId(Objects.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG_, Namespaces.umatiConnect);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class ObjectTypeIds
    {
    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all ReferenceTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Variables in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_Manufacturer Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_Manufacturer = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Identification_Manufacturer, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_ProductInstanceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_ProductInstanceUri = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Identification_ProductInstanceUri, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_SerialNumber Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_SerialNumber = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Identification_SerialNumber, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_Identifier Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_Identifier = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_Identifier, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_SoftwareRevision Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_SoftwareRevision = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Identification_SoftwareIdentification_MDC_SoftwareRevision, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EngineeringUnits Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EngineeringUnits = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EngineeringUnits, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EURange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EURange = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_FeedOverride_EURange, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_EffectiveDisplayName Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_EffectiveDisplayName = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_EffectiveDisplayName, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Id Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Id = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Id, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Name Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Name = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Name, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Number Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Number = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_MachineryItemState_CurrentState_Number, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_OperationDuration Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_OperationDuration = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_OperationDuration, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_PowerOnDuration Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_PowerOnDuration = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_OperationCounters_PowerOnDuration, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_MachineTool_OperationMode Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_MachineTool_OperationMode = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_MachineTool_OperationMode, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_NumberInList Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_NumberInList = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_NumberInList, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalColor Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalColor = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalColor, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalMode Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalMode = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalMode, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalOn Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalOn = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_1_SignalOn, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_NumberInList Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_NumberInList = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_NumberInList, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalColor Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalColor = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalColor, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalMode Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalMode = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalMode, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalOn Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalOn = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_2_SignalOn, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_NumberInList Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_NumberInList = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_NumberInList, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalColor Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalColor = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalColor, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalMode Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalMode = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalMode, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalOn Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalOn = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_3_SignalOn, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_NumberInList Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_NumberInList = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_NumberInList, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalColor Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalColor = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalColor, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalMode Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalMode = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalMode, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalOn Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalOn = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_Light_4_SignalOn, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Monitoring_Stacklight_StacklightMode Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Monitoring_Stacklight_StacklightMode = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Monitoring_Stacklight_StacklightMode, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Notification_EmergencyStopTriggered Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Notification_EmergencyStopTriggered = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Notification_EmergencyStopTriggered, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_CurrentRunTime Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_CurrentRunTime = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_CurrentRunTime, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_DesiredParts Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_DesiredParts = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_DesiredParts, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_JobIdentifier Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_JobIdentifier = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_JobIdentifier, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_Name Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_Name = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_Name, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_NumberInList Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_NumberInList = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_NumberInList, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_PartCounter Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_PartCounter = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_PartCounter, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Id Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Id = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Id, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Number Variable.
        /// </summary>
        public static readonly ExpandedNodeId Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Number = new ExpandedNodeId(Variables.Machines_DMGMilltap700_Production_ActiveProgram_State_CurrentState_Number, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__IsNamespaceSubset Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__IsNamespaceSubset = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__IsNamespaceSubset, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespacePublicationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespacePublicationDate = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespacePublicationDate, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceUri = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceUri, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceVersion Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceVersion = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__NamespaceVersion, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNodeIdTypes Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNodeIdTypes = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNodeIdTypes, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNumericNodeIdRange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNumericNodeIdRange = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticNumericNodeIdRange, Namespaces.umatiConnect);

        /// <summary>
        /// The identifier for the Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticStringNodeIdPattern Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticStringNodeIdPattern = new ExpandedNodeId(Variables.Namespaces_http___ifw_uni_hannover_de_umatiConnectDMG__StaticStringNodeIdPattern, Namespaces.umatiConnect);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all VariableType in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.7.0")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the CurrentRunTime component.
        /// </summary>
        public const string CurrentRunTime = "CurrentRunTime";
        /// <summary>
        /// The BrowseName for the DMGMilltap700 component.
        /// </summary>
        public const string DMGMilltap700 = "DMGMilltap700";
        /// <summary>
        /// The BrowseName for the DesiredParts component.
        /// </summary>
        public const string DesiredParts = "DesiredParts";
        /// <summary>
        /// The BrowseName for the EmergencyStopTriggered component.
        /// </summary>
        public const string EmergencyStopTriggered = "EmergencyStopTriggered";
        /// <summary>
        /// The BrowseName for the Light_2 component.
        /// </summary>
        public const string Light_2 = "Light_2";
        /// <summary>
        /// The BrowseName for the Light_3 component.
        /// </summary>
        public const string Light_3 = "Light_3";
        /// <summary>
        /// The BrowseName for the Light_4 component.
        /// </summary>
        public const string Light_4 = "Light_4";
        /// <summary>
        /// The BrowseName for the PartCounter component.
        /// </summary>
        public const string PartCounter = "PartCounter";
        /// <summary>
        /// The BrowseName for the http://ifw.uni-hannover.de/umatiConnectDMG/ component.
        /// </summary>
        public const string http___ifw_uni_hannover_de_umatiConnectDMG_ = "http://ifw.uni-hannover.de/umatiConnectDMG/";
    }
    #endregion

    #region AbsolueName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class AbsoluteNames
    {
        /// <summary>
        /// The AbsoluteName for the CurrentRunTime component.
        /// </summary>
        public static readonly AbsoluteName CurrentRunTime = new AbsoluteName(BrowseNames.CurrentRunTime, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the DMGMilltap700 component.
        /// </summary>
        public static readonly AbsoluteName DMGMilltap700 = new AbsoluteName(BrowseNames.DMGMilltap700, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the DesiredParts component.
        /// </summary>
        public static readonly AbsoluteName DesiredParts = new AbsoluteName(BrowseNames.DesiredParts, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the EmergencyStopTriggered component.
        /// </summary>
        public static readonly AbsoluteName EmergencyStopTriggered = new AbsoluteName(BrowseNames.EmergencyStopTriggered, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the Light_2 component.
        /// </summary>
        public static readonly AbsoluteName Light_2 = new AbsoluteName(BrowseNames.Light_2, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the Light_3 component.
        /// </summary>
        public static readonly AbsoluteName Light_3 = new AbsoluteName(BrowseNames.Light_3, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the Light_4 component.
        /// </summary>
        public static readonly AbsoluteName Light_4 = new AbsoluteName(BrowseNames.Light_4, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the PartCounter component.
        /// </summary>
        public static readonly AbsoluteName PartCounter = new AbsoluteName(BrowseNames.PartCounter, Namespaces.umatiConnect);
        /// <summary>
        /// The AbsoluteName for the http://ifw.uni-hannover.de/umatiConnectDMG/ component.
        /// </summary>
        public static readonly AbsoluteName http___ifw_uni_hannover_de_umatiConnectDMG_ = new AbsoluteName(BrowseNames.http___ifw_uni_hannover_de_umatiConnectDMG_, Namespaces.umatiConnect);
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the umatiConnect namespace.
        /// </summary>
        public const string umatiConnect = "http://ifw.uni-hannover.de/umatiConnectDMG/";

        /// <summary>
        /// The URI for the umatiConnectXsd namespace.
        /// </summary>
        public const string umatiConnectXsd = "http://ifw.uni-hannover.de/umatiConnectDMG/Types.xsd";
    }
    #endregion
}

